# Generated by Django 3.2.16 on 2022-12-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='list_data',
            new_name='list_date',
        ),
    ]
